name: ci

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read
  actions: write

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: '20'
          cache: npm
      - run: npm ci
      - run: npm run build
      - run: npm run lint:sol
      - run: npm run test
      - run: npm run coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7
        with:
          files: coverage/lcov.info
          flags: solidity
          name: solidity-coverage
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
      - run: npm run gas | tee gas-report.txt
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: gas-report
          path: |
            gas-report.txt
            gasReporterOutput.json
          if-no-files-found: warn
      - run: npm run export:artifacts
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: artifacts-public
          path: artifacts-public
