name: deploy-testnet

on:
  workflow_dispatch:
    inputs:
      network:
        description: 'Target network'
        required: false
        default: sepolia

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: '20'
      - run: npm ci
      - run: npm run namehash
      - run: NETWORK=${{ github.event.inputs.network || 'sepolia' }} npm run migrate:sepolia
        env:
          MNEMONIC: ${{ secrets.MNEMONIC }}
          RPC_SEPOLIA: ${{ secrets.RPC_SEPOLIA }}
          GOV_SAFE: ${{ secrets.GOV_SAFE }}
          TIMELOCK_ADDR: ${{ secrets.TIMELOCK_ADDR }}
      - run: NETWORK=${{ github.event.inputs.network || 'sepolia' }} npm run verify:sepolia
        env:
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
      - run: NETWORK=${{ github.event.inputs.network || 'sepolia' }} npm run export:artifacts
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: artifacts-public
          path: artifacts-public
