name: echidna-smoke

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  fuzz:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: '20'
      - run: npm ci
      - name: Install Echidna
        run: |
          sudo add-apt-repository ppa:ethereum/ethereum -y
          sudo apt-get update
          sudo apt-get install -y echidna
      - name: Run Echidna smoke
        run: echidna-test ./contracts/core --test-mode assertion --corpus-dir=echidna-corpus --max-steps=500
