name: slither

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: '20'
      - run: npm ci
      - name: Run Slither
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/src \
            -w /src \
            trailofbits/slither:latest \
            sh -c "python3 -m pip install --no-cache-dir 'slither-analyzer>=0.10.4' && slither . --fail-medium"
